apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app.kubernetes.io/name: composable-operator
  name: composable-operator
  namespace: composable-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composable-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: composable-operator
    spec:
      containers:
      - command:
        - ./manager
        image: cloudoperators/composable-controller:0.1.5
        imagePullPolicy: Always
        name: composable
      serviceAccountName: composable-operator
