apiVersion:  apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/name: composable-operator 
  name: composable-operator
  namespace: composable-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composable-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: composable-operator
    spec:
      containers:
      - args:
        - "-logtostderr=true"
        - "-v=5"
        command:
        - ./manager
        image: PLACEHOLDER
        imagePullPolicy: Always
        name: composable-controller
      serviceAccountName: composable-operator